"""Seven-archetype, two-profile deterministic scaffold renderer."""

import re
from pathlib import Path
from typing import Any, Dict, List, Optional

from .adapters import ADAPTER_SPECS, CSV_FORMATS, PANDAS_FORMATS
from .archetypes import ARCHETYPE_IDS, ARCHETYPE_SPECS
from .canonical import (
    create_or_verify_bytes,
    create_or_verify_json,
    hash_object,
    read_json,
    sha256_bytes,
)
from .contracts import PROFILES as CONTRACT_PROFILES
from .contracts import StrategySpec
from .errors import AgentError
from .tokens import TokenAuthority

ARCHETYPES = tuple(sorted(ARCHETYPE_IDS))
ARCHETYPE_CODE = {name: spec.template for name, spec in ARCHETYPE_SPECS.items()}
PROFILES = tuple(sorted(CONTRACT_PROFILES))
SESSION_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{1,79}$")
HASH_RE = re.compile(r"^[0-9a-f]{64}$")


def load_product_artifact_record(
    state_root: Path,
    session_id: str,
    artifact_hash: str,
    authority: TokenAuthority,
) -> Dict[str, Any]:
    """Load and authenticate the renderer-owned provenance record."""

    if not SESSION_RE.fullmatch(session_id) or not HASH_RE.fullmatch(artifact_hash):
        raise AgentError(
            "BTAG-PROVENANCE-ID", "artifact provenance identifiers are malformed"
        )
    path = (
        Path(state_root)
        / "sessions"
        / session_id
        / "artifacts"
        / f"{artifact_hash}.json"
    )
    if not path.is_file() or path.is_symlink():
        raise AgentError(
            "BTAG-PROVENANCE-MISSING",
            "artifact was not generated by the product renderer for this session",
        )
    record = read_json(path)
    payload = authority.verify_product_record(record)
    expected_hash = payload.get("record_hash")
    actual_hash = hash_object(
        {key: value for key, value in payload.items() if key != "record_hash"}
    )
    if expected_hash != actual_hash:
        raise AgentError(
            "BTAG-PROVENANCE-HASH", "artifact provenance record hash is invalid"
        )
    if (
        payload.get("schema_version") != "artifact-provenance-v1"
        or payload.get("generated_by") != "backtrader-agent"
        or payload.get("renderer_version") != "scaffold-v1"
        or payload.get("session_id") != session_id
        or payload.get("artifact_hash") != artifact_hash
    ):
        raise AgentError(
            "BTAG-PROVENANCE-BINDING", "artifact provenance record is inconsistent"
        )
    return payload


def _strategy_source(spec: StrategySpec) -> str:
    init_body, next_body = ARCHETYPE_CODE[spec.archetype]
    if spec.value.get("sizing"):
        # With an active sizing block, entry orders delegate their stake to
        # the sizer installed by the runner assembly. The fixed template's
        # explicit ``size=1`` would bypass any sizer (both stock Backtrader
        # and the bound fork use the explicit size verbatim).
        next_body = next_body.replace("(size=1)", "()").replace(", size=1)", ")")
    fast = int(spec.parameter_defaults.get("fast_period", 5))
    slow = int(spec.parameter_defaults.get("slow_period", 12))
    return f'''"""Generated by backtrader-agent from StrategySpec {spec.spec_hash}."""
import backtrader as bt


class GeneratedStrategy(bt.Strategy):
    params = (
        ("fast_period", {fast}),
        ("slow_period", {slow}),
    )

    def __init__(self):
{init_body}
        self._agent_buy_count = 0
        self._agent_sell_count = 0

    def next(self):
{next_body}

    def notify_order(self, order):
        if order.status == order.Completed:
            if order.isbuy():
                self._agent_buy_count += 1
            elif order.issell():
                self._agent_sell_count += 1
'''


def _pandas_custom_feed_source(dataset: Dict[str, Any]) -> str:
    classes = []
    branches = []
    for index, feed in enumerate(dataset.get("feeds", [])):
        if feed.get("format") != "pandas_custom_lines":
            continue
        canonical_columns = list(feed.get("canonical_columns", []))
        custom_lines = tuple(canonical_columns[7:])
        class_name = f"AgentPandasData{index}"
        parameters = tuple((line_name, line_name) for line_name in custom_lines)
        if custom_lines:
            classes.append(
                f"class {class_name}(bt.feeds.PandasData):\n"
                f"    lines = {custom_lines!r}\n"
                f"    params = {parameters!r}\n"
            )
        else:
            class_name = "bt.feeds.PandasData"
        branches.append(
            f'    if feed_name == {feed["name"]!r}:\n' f"        return {class_name}\n"
        )
    body = "\n\n".join(classes)
    if body:
        body += "\n\n"
    return (
        body
        + "def _pandas_custom_feed_class(feed_name):\n"
        + "".join(branches)
        + '    raise RuntimeError("custom Pandas feed was not rendered for this dataset")\n'
    )


_CSV_BRANCHES = "\n".join(ADAPTER_SPECS[name].assembly for name in CSV_FORMATS)
_CSV_FORMAT_SET = (
    "{\n" + "".join(f'        "{name}",\n' for name in CSV_FORMATS) + "    }"
)
_PANDAS_FORMAT_SET = "{" + ", ".join(f'"{name}"' for name in PANDAS_FORMATS) + "}"
_PANDAS_CUSTOM_ASSEMBLY = ADAPTER_SPECS["pandas_custom_lines"].assembly
_PANDAS_DEFAULT_ASSEMBLY = ADAPTER_SPECS["pandas"].assembly


_MAIN_HARNESS_BLOCK = (
    'if __name__ == "__main__":\n'
    '    print("BACKTRADER_AGENT_RESULT=" + json.dumps(_execute(), sort_keys=True))\n'
)


def _sizing_assembly(sizing: Optional[Dict[str, Any]]) -> str:
    """Render the fixed cerebro.addsizer assembly for the validated sizing block.

    Returns an empty string when sizing is null so a spec without a sizing
    block keeps Backtrader's default sizer, exactly as before R24.

    The bound engine fork's ``Cerebro.addsizer`` takes the sizer *class*
    plus constructor arguments (it instantiates in ``runstrategies``), so
    the assembly passes ``bt.sizers.FixedSize`` / ``bt.sizers.PercentSizer``
    as classes; this form also works on stock Backtrader.
    """

    if not sizing:
        return ""
    if sizing["method"] == "fixed":
        return (
            "cerebro.addsizer(bt.sizers.FixedSize, "
            f"stake={sizing['fixed_size']!r})\n    "
        )
    return (
        "cerebro.addsizer(bt.sizers.PercentSizer, "
        f"percents={sizing['percent']!r})\n    "
    )


_SINGLE_TEST_HARNESS_BLOCK = (
    "def test_generated_strategy():\n"
    "    result = _execute()\n"
    '    assert result["metrics"]["final_value"] is not None\n'
    '    print("BACKTRADER_AGENT_RESULT=" + json.dumps(result, sort_keys=True))\n'
)

_RUNNER_SOURCE_TEMPLATE = '''"""Controlled child-process entrypoint generated by backtrader-agent."""
import json
import math
import os

import backtrader as bt
import pandas as pd
from backtrader import TimeFrame

{strategy_import}
TIMEFRAMES = {{
    "Ticks": TimeFrame.Ticks,
    "MicroSeconds": TimeFrame.MicroSeconds,
    "Seconds": TimeFrame.Seconds,
    "Minutes": TimeFrame.Minutes,
    "Days": TimeFrame.Days,
    "Weeks": TimeFrame.Weeks,
    "Months": TimeFrame.Months,
    "Years": TimeFrame.Years,
}}


class CanonicalBacktraderCSVData(bt.feeds.BacktraderCSVData):
    """Load canonical CAS rows through Backtrader's fixed CSV parser."""

    def _loadline(self, tokens):
        native = list(tokens[:7])
        native[0] = native[0][:10]
        return super()._loadline(native)


class CanonicalYahooCSVData(bt.feeds.YahooFinanceCSVData):
    """Adapt canonical CAS rows to the offline Yahoo parser contract."""

    def _loadline(self, tokens):
        native = [
            tokens[0][:10],
            tokens[1],
            tokens[2],
            tokens[3],
            tokens[4],
            tokens[4],
            tokens[5],
        ]
        return super()._loadline(native)


class CanonicalMT5CSVData(bt.feeds.GenericCSVData):
    """Controlled MT5 materialization adapter; input is already canonical CAS."""


{custom_feed_source}


def _csv_feed(descriptor):
    common = {{
        "dataname": descriptor["path"],
        "headers": True,
        "timeframe": TIMEFRAMES[descriptor["timeframe"]],
        "compression": descriptor["compression"],
    }}
    adapter = descriptor["adapter"]
{csv_branches}
    raise RuntimeError("CSV dataset adapter is not product-allowlisted")


def _pandas_feed(descriptor):
    frame = pd.read_csv(
        descriptor["path"],
        parse_dates=["datetime"],
    )
    feed_class = (
        {pandas_custom_assembly}
        if descriptor["adapter"] == "pandas_custom_lines"
        else {pandas_default_assembly}
    )
    parameters = {{
        "dataname": frame,
        "datetime": "datetime",
        "open": "open",
        "high": "high",
        "low": "low",
        "close": "close",
        "volume": "volume",
        "openinterest": "openinterest",
        "timeframe": TIMEFRAMES[descriptor["timeframe"]],
        "compression": descriptor["compression"],
    }}
    return feed_class(**parameters)


def _load_feed(descriptor):
    adapter = descriptor["adapter"]
    if adapter in {csv_format_set}:
        return _csv_feed(descriptor)
    if adapter in {pandas_format_set}:
        return _pandas_feed(descriptor)
    raise RuntimeError("dataset adapter is not product-allowlisted")


def _nested(value, *parts, default=None):
    current = value
    for part in parts:
        if not isinstance(current, dict) or part not in current:
            return default
        current = current[part]
    return current


def _finite_number(value):
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if math.isfinite(number) else None


def _last_series_value(series):
    if isinstance(series, dict) and series:
        return series[list(series)[-1]]
    if isinstance(series, (list, tuple)) and series:
        return series[-1]
    return series


def _positions_value_total(series):
    entry = _last_series_value(series)
    if isinstance(entry, (list, tuple)):
        return _finite_number(sum(_finite_number(item) or 0.0 for item in entry))
    if isinstance(entry, dict):
        return _finite_number(
            sum(_finite_number(item) or 0.0 for item in entry.values())
        )
    return _finite_number(entry)


def _safe_analyzer(base):
    class _SafeAnalyzer(base):
        def _next(self):
            try:
                super()._next()
            except Exception:
                pass

        def next(self):
            try:
                super().next()
            except Exception:
                pass

        def _stop(self):
            try:
                super()._stop()
            except Exception:
                pass

        def stop(self):
            try:
                super().stop()
            except Exception:
                pass

    return _SafeAnalyzer


def _trade_analyzer_subset(trade):
    won_total = float(_nested(trade, "won", "pnl", "total", default=0.0) or 0.0)
    lost_total = float(_nested(trade, "lost", "pnl", "total", default=0.0) or 0.0)
    if lost_total:
        profit_factor = _finite_number(won_total / abs(lost_total))
    else:
        profit_factor = None
    return {{
        "profit_factor": profit_factor,
        "avg_holding_bars": _finite_number(_nested(trade, "len", "average")),
        "max_consecutive_wins": _finite_number(
            _nested(trade, "streak", "won", "longest", default=0)
        ),
        "max_consecutive_losses": _finite_number(
            _nested(trade, "streak", "lost", "longest", default=0)
        ),
    }}


def _extended_metrics(strategy, trade):
    try:
        trade_analyzer = _trade_analyzer_subset(trade)
    except Exception:
        trade_analyzer = None
    try:
        sqn = strategy.analyzers.sqn.get_analysis()
        sqn = _finite_number(sqn.get("sqn") if isinstance(sqn, dict) else None)
    except Exception:
        sqn = None
    try:
        calmar = strategy.analyzers.calmar.get_analysis()
        calmar = _finite_number(_last_series_value(calmar))
    except Exception:
        calmar = None
    try:
        vwr = strategy.analyzers.vwr.get_analysis()
        vwr = _finite_number(vwr.get("vwr") if isinstance(vwr, dict) else None)
    except Exception:
        vwr = None
    try:
        leverage = strategy.analyzers.gross_leverage.get_analysis()
        leverage = _finite_number(_last_series_value(leverage))
    except Exception:
        leverage = None
    try:
        positions = strategy.analyzers.positions_value.get_analysis()
        positions = _positions_value_total(positions)
    except Exception:
        positions = None
    return {{
        "trade_analyzer": trade_analyzer,
        "sqn": sqn,
        "calmar": calmar,
        "vwr": vwr,
        "gross_leverage": leverage,
        "positions_value": positions,
    }}


def _execute():
    descriptors = json.loads(os.environ["BACKTRADER_AGENT_DATASETS_JSON"])
    mode = os.environ.get("BACKTRADER_AGENT_MODE", "runonce")
    cerebro = bt.Cerebro(stdstats=False)
    for descriptor in descriptors:
        feed = _load_feed(descriptor)
        transform = descriptor.get("transform")
        if transform is None:
            cerebro.adddata(feed, name=descriptor["name"])
        else:
            parameters = transform["parameters"]
            if transform["profile_id"] == "resample":
                cerebro.resampledata(
                    feed,
                    name=descriptor["name"],
                    timeframe=TIMEFRAMES[parameters["timeframe"]],
                    compression=parameters["compression"],
                )
            elif transform["profile_id"] == "replay":
                cerebro.replaydata(
                    feed,
                    name=descriptor["name"],
                    timeframe=TIMEFRAMES[parameters["timeframe"]],
                    compression=parameters["compression"],
                )
            else:
                raise RuntimeError("dataset transform is not product-allowlisted")
    start_cash = {cash!r}
    cerebro.broker.setcash(start_cash)
    cerebro.broker.setcommission(commission={commission!r})
    {sizing_assembly}cerebro.addstrategy(GeneratedStrategy)
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name="trades")
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name="drawdown")
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name="sharpe")
    cerebro.addanalyzer(bt.analyzers.Returns, _name="returns")
    try:
        cerebro.addanalyzer(_safe_analyzer(bt.analyzers.SQN), _name="sqn")
    except Exception:
        pass
    try:
        cerebro.addanalyzer(_safe_analyzer(bt.analyzers.Calmar), _name="calmar")
    except Exception:
        pass
    try:
        cerebro.addanalyzer(_safe_analyzer(bt.analyzers.VWR), _name="vwr")
    except Exception:
        pass
    try:
        cerebro.addanalyzer(
            _safe_analyzer(bt.analyzers.GrossLeverage), _name="gross_leverage"
        )
    except Exception:
        pass
    try:
        cerebro.addanalyzer(
            _safe_analyzer(bt.analyzers.PositionsValue), _name="positions_value"
        )
    except Exception:
        pass
    strategies = cerebro.run(runonce=(mode == "runonce"))
    strategy = strategies[0]
    trade = strategy.analyzers.trades.get_analysis()
    drawdown = strategy.analyzers.drawdown.get_analysis()
    sharpe = strategy.analyzers.sharpe.get_analysis()
    returns = strategy.analyzers.returns.get_analysis()
    final_value = float(cerebro.broker.getvalue())
    trade_count = int(_nested(trade, "total", "closed", default=0) or 0)
    won = int(_nested(trade, "won", "total", default=0) or 0)
    lost = int(_nested(trade, "lost", "total", default=0) or 0)
    metrics = {{
        "bar_num": int(len(strategy)),
        "buy_count": int(strategy._agent_buy_count),
        "sell_count": int(strategy._agent_sell_count),
        "win_count": won,
        "loss_count": lost,
        "trade_num": trade_count,
        "final_value": final_value,
        "sharpe_ratio": sharpe.get("sharperatio") if isinstance(sharpe, dict) else None,
        "annual_return": float(returns.get("rnorm", 0.0) or 0.0),
        "max_drawdown": float(_nested(drawdown, "max", "drawdown", default=0.0) or 0.0),
        "return_rate": ((final_value / start_cash - 1.0) * 100.0) if start_cash else 0.0,
    }}
    for value in metrics.values():
        if isinstance(value, float) and not math.isfinite(value):
            raise RuntimeError("non-finite metric")
    return {{"metrics": metrics, "extended_metrics": _extended_metrics(strategy, trade)}}


{harness_block}'''


def _runner_source(spec: StrategySpec, dataset: Dict[str, Any]) -> str:
    return _RUNNER_SOURCE_TEMPLATE.format(
        strategy_import=f"from strategy_{spec.module_slug} import GeneratedStrategy\n\n",
        custom_feed_source=_pandas_custom_feed_source(dataset),
        csv_branches=_CSV_BRANCHES,
        csv_format_set=_CSV_FORMAT_SET,
        pandas_format_set=_PANDAS_FORMAT_SET,
        pandas_custom_assembly=_PANDAS_CUSTOM_ASSEMBLY,
        pandas_default_assembly=_PANDAS_DEFAULT_ASSEMBLY,
        cash=float(spec.value.get("cash", 100000.0)),
        commission=float(spec.value.get("commission", 0.0)),
        sizing_assembly=_sizing_assembly(spec.value.get("sizing")),
        harness_block=_MAIN_HARNESS_BLOCK,
    )


_SINGLE_TEST_TEMPLATE = "{strategy_source}\n\n" + _RUNNER_SOURCE_TEMPLATE


def _render_single_test_source(
    strategy_source: str,
    *,
    custom_feed_source: str = "",
    cash: float = 100000.0,
    commission: float = 0.0,
    sizing_assembly: str = "",
) -> str:
    """Render the single-test profile source by template interpolation.

    ``{strategy_source}`` plus the parameterized runner-body placeholders
    replace the three ``str.replace`` splices of the previous
    ``_single_test_source``; the renderer passes the spec- and
    dataset-dependent values so the rendered bytes stay identical.
    """

    return _SINGLE_TEST_TEMPLATE.format(
        strategy_source=strategy_source,
        strategy_import="",
        custom_feed_source=custom_feed_source,
        csv_branches=_CSV_BRANCHES,
        csv_format_set=_CSV_FORMAT_SET,
        pandas_format_set=_PANDAS_FORMAT_SET,
        pandas_custom_assembly=_PANDAS_CUSTOM_ASSEMBLY,
        pandas_default_assembly=_PANDAS_DEFAULT_ASSEMBLY,
        cash=cash,
        commission=commission,
        sizing_assembly=sizing_assembly,
        harness_block=_SINGLE_TEST_HARNESS_BLOCK,
    )


def _config_source(spec: StrategySpec, dataset: Dict[str, Any]) -> str:
    return f"""schema_version: generated-config-v1
strategy:
  name: {spec.value['name']}
  slug: {spec.slug}
  archetype: {spec.archetype}
dataset_id: {dataset['dataset_id']}
dataset_manifest_hash: {dataset['manifest_hash']}
cash: {float(spec.value.get('cash', 100000.0))}
commission: {float(spec.value.get('commission', 0.0))}
execution_modes:
  - runonce
  - runnext
"""


class ArtifactRenderer:
    def __init__(self, state_root: Path) -> None:
        self.state_root = Path(state_root)

    def render(
        self,
        session_id: str,
        spec: StrategySpec,
        dataset: Dict[str, Any],
        *,
        draft_root: Optional[Path] = None,
    ) -> Dict[str, Any]:
        if not SESSION_RE.fullmatch(session_id):
            raise AgentError("BTAG-SESSION-ID", "session ID is malformed")
        if dataset.get("dataset_id") != spec.value["dataset_id"]:
            raise AgentError(
                "BTAG-RENDER-DATASET", "StrategySpec dataset ID does not match"
            )
        revision = hash_object(
            {
                "spec_hash": spec.spec_hash,
                "dataset_hash": dataset.get("manifest_hash"),
                "renderer": "scaffold-v1",
            }
        )[:20]
        if draft_root is None:
            draft_root = self.state_root / "sessions" / session_id / "drafts" / revision
        else:
            # Renderer-owned private drafts may live elsewhere under the state
            # root (sweep cells render into their sealed cell directory); the
            # provenance record keeps the state-relative location bound either
            # way.
            draft_root = Path(draft_root)
        if spec.profile == "python_bundle":
            file_contents = {
                "config.yaml": _config_source(spec, dataset).encode("utf-8"),
                f"strategy_{spec.module_slug}.py": _strategy_source(spec).encode(
                    "utf-8"
                ),
                "run.py": _runner_source(spec, dataset).encode("utf-8"),
            }
            roles = {
                "config.yaml": "config",
                f"strategy_{spec.module_slug}.py": "strategy",
                "run.py": "runner",
            }
            entrypoint = "run.py"
        else:
            name = f"test_{spec.slug}.py"
            file_contents = {
                name: _render_single_test_source(
                    _strategy_source(spec),
                    custom_feed_source=_pandas_custom_feed_source(dataset),
                    cash=float(spec.value.get("cash", 100000.0)),
                    commission=float(spec.value.get("commission", 0.0)),
                    sizing_assembly=_sizing_assembly(spec.value.get("sizing")),
                ).encode("utf-8")
            }
            roles = {name: "strategy"}
            entrypoint = name
        draft_root.mkdir(parents=True, exist_ok=True)
        files: List[Dict[str, Any]] = []
        for relative_path, content in sorted(file_contents.items()):
            destination = draft_root / relative_path
            create_or_verify_bytes(
                destination,
                content,
                conflict_code="BTAG-DRAFT-CONFLICT",
                conflict_message="draft revision has conflicting bytes",
            )
            files.append(
                {
                    "path": relative_path,
                    "role": roles[relative_path],
                    "sha256": sha256_bytes(content),
                    "bytes": len(content),
                }
            )
        portable = {
            "schema_version": "artifact-manifest-v1",
            "artifact_id": f"artifact-{revision}",
            "slug": spec.slug,
            "spec_hash": spec.spec_hash,
            "dataset_id": dataset["dataset_id"],
            "output_profile": spec.profile,
            "files": files,
            "extensions": {
                "backtrader_agent": {
                    "generated_by": "backtrader-agent",
                    "renderer_version": "scaffold-v1",
                    "session_id": session_id,
                    "archetype": spec.archetype,
                    "dataset_manifest_hash": dataset["manifest_hash"],
                    "entrypoint": entrypoint,
                }
            },
        }
        portable["artifact_hash"] = hash_object(portable)
        manifest_path = draft_root / "artifact-manifest.json"
        create_or_verify_json(
            manifest_path,
            portable,
            conflict_code="BTAG-DRAFT-MANIFEST",
            conflict_message="draft manifest conflicts",
        )
        state_root = self.state_root.resolve()
        resolved_draft = draft_root.resolve(strict=True)
        try:
            draft_relative = resolved_draft.relative_to(state_root).as_posix()
        except ValueError as exc:
            raise AgentError(
                "BTAG-DRAFT-PATH", "private draft must remain inside state root"
            ) from exc
        record_payload: Dict[str, Any] = {
            "schema_version": "artifact-provenance-v1",
            "generated_by": "backtrader-agent",
            "renderer_version": "scaffold-v1",
            "session_id": session_id,
            "artifact_hash": portable["artifact_hash"],
            "spec_hash": spec.spec_hash,
            "dataset_id": dataset["dataset_id"],
            "dataset_manifest_hash": dataset["manifest_hash"],
            "draft_relative_path": draft_relative,
            "manifest_sha256": sha256_bytes(manifest_path.read_bytes()),
        }
        record_payload["record_hash"] = hash_object(record_payload)
        record = {
            **record_payload,
            "signature": TokenAuthority(self.state_root).sign_product_record(
                record_payload
            ),
        }
        record_path = (
            self.state_root
            / "sessions"
            / session_id
            / "artifacts"
            / f"{portable['artifact_hash']}.json"
        )
        create_or_verify_json(
            record_path,
            record,
            conflict_code="BTAG-PROVENANCE-CONFLICT",
            conflict_message="artifact provenance record conflicts with the rendered bytes",
        )
        return {
            **portable,
            "_draft_path": str(draft_root),
            "_artifact_record_hash": record_payload["record_hash"],
        }
