"""Seven-archetype, two-profile deterministic scaffold renderer."""

import re
from pathlib import Path
from typing import Any, Dict, List

from .canonical import (
    atomic_write_bytes,
    atomic_write_json,
    canonical_json_bytes,
    hash_object,
    read_json,
    sha256_bytes,
)
from .contracts import ARCHETYPES as CONTRACT_ARCHETYPES
from .contracts import PROFILES as CONTRACT_PROFILES
from .contracts import StrategySpec
from .errors import AgentError
from .tokens import TokenAuthority

ARCHETYPES = tuple(sorted(CONTRACT_ARCHETYPES))
PROFILES = tuple(sorted(CONTRACT_PROFILES))
SESSION_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{1,79}$")
HASH_RE = re.compile(r"^[0-9a-f]{64}$")


def load_product_artifact_record(
    state_root: Path,
    session_id: str,
    artifact_hash: str,
    authority: TokenAuthority,
) -> Dict[str, Any]:
    """Load and authenticate the renderer-owned provenance record."""

    if not SESSION_RE.fullmatch(session_id) or not HASH_RE.fullmatch(artifact_hash):
        raise AgentError("BTAG-PROVENANCE-ID", "artifact provenance identifiers are malformed")
    path = Path(state_root) / "sessions" / session_id / "artifacts" / f"{artifact_hash}.json"
    if not path.is_file() or path.is_symlink():
        raise AgentError(
            "BTAG-PROVENANCE-MISSING",
            "artifact was not generated by the product renderer for this session",
        )
    record = read_json(path)
    payload = authority.verify_product_record(record)
    expected_hash = payload.get("record_hash")
    actual_hash = hash_object(
        {key: value for key, value in payload.items() if key != "record_hash"}
    )
    if expected_hash != actual_hash:
        raise AgentError("BTAG-PROVENANCE-HASH", "artifact provenance record hash is invalid")
    if (
        payload.get("schema_version") != "artifact-provenance-v1"
        or payload.get("generated_by") != "backtrader-agent"
        or payload.get("renderer_version") != "scaffold-v1"
        or payload.get("session_id") != session_id
        or payload.get("artifact_hash") != artifact_hash
    ):
        raise AgentError("BTAG-PROVENANCE-BINDING", "artifact provenance record is inconsistent")
    return payload


ARCHETYPE_CODE = {
    "single_data_indicator": (
        """        self.fast = bt.ind.SMA(self.data.close, period=self.p.fast_period)
        self.slow = bt.ind.SMA(self.data.close, period=self.p.slow_period)""",
        """        if not self.position and self.fast[0] > self.slow[0]:
            self.buy(size=1)
        elif self.position and self.fast[0] < self.slow[0]:
            self.close()""",
    ),
    "multi_indicator_system": (
        """        self.fast = bt.ind.EMA(self.data.close, period=self.p.fast_period)
        self.slow = bt.ind.SMA(self.data.close, period=self.p.slow_period)
        self.rsi = bt.ind.RSI(self.data.close, period=max(2, self.p.fast_period))""",
        """        if not self.position and self.fast[0] > self.slow[0] and self.rsi[0] < 70:
            self.buy(size=1)
        elif self.position and (self.fast[0] < self.slow[0] or self.rsi[0] > 75):
            self.close()""",
    ),
    "multi_asset_allocation": (
        """        self.execution_data = self.datas[0]
        self.signal_data = self.datas[1] if len(self.datas) > 1 else self.datas[0]
        self.signal_sma = bt.ind.SMA(self.signal_data.close, period=self.p.fast_period)""",
        """        if not self.getposition(self.execution_data) and self.signal_data.close[0] > self.signal_sma[0]:
            self.buy(data=self.execution_data, size=1)
        elif self.getposition(self.execution_data) and self.signal_data.close[0] < self.signal_sma[0]:
            self.close(data=self.execution_data)""",
    ),
    "multi_timeframe": (
        """        self.execution_data = self.datas[0]
        self.higher_timeframe = self.datas[1] if len(self.datas) > 1 else self.datas[0]
        self.higher_sma = bt.ind.SMA(self.higher_timeframe.close, period=self.p.fast_period)""",
        """        if not self.position and self.higher_timeframe.close[0] > self.higher_sma[0]:
            self.buy(data=self.execution_data, size=1)
        elif self.position and self.higher_timeframe.close[0] < self.higher_sma[0]:
            self.close(data=self.execution_data)""",
    ),
    "pairs_spread": (
        """        self.leg_a = self.datas[0]
        self.leg_b = self.datas[1] if len(self.datas) > 1 else self.datas[0]
        self.spread = self.leg_a.close - self.leg_b.close
        self.spread_mean = bt.ind.SMA(self.spread, period=self.p.fast_period)""",
        """        deviation = self.spread[0] - self.spread_mean[0]
        if not self.getposition(self.leg_a) and deviation < 0:
            self.buy(data=self.leg_a, size=1)
            if self.leg_b is not self.leg_a:
                self.sell(data=self.leg_b, size=1)
        elif self.getposition(self.leg_a) and deviation >= 0:
            self.close(data=self.leg_a)
            if self.leg_b is not self.leg_a:
                self.close(data=self.leg_b)""",
    ),
    "order_risk": (
        """        self.signal = bt.ind.SMA(self.data.close, period=self.p.fast_period)
        self.atr = bt.ind.ATR(self.data, period=max(2, self.p.fast_period))
        self.entry_price = None""",
        """        if not self.position and self.data.close[0] > self.signal[0]:
            self.buy(size=1)
            self.entry_price = float(self.data.close[0])
        elif self.position:
            stop = self.entry_price - 2.0 * float(self.atr[0])
            if self.data.close[0] < self.signal[0] or self.data.close[0] <= stop:
                self.close()
                self.entry_price = None""",
    ),
    "precomputed_ml": (
        """        if not hasattr(self.data, "signal"):
            raise RuntimeError("registered dataset must expose the precomputed signal line")
        self.model_signal = self.data.signal""",
        """        if not self.position and self.model_signal[0] > 0:
            self.buy(size=1)
        elif self.position and self.model_signal[0] <= 0:
            self.close()""",
    ),
}


def _strategy_source(spec: StrategySpec) -> str:
    init_body, next_body = ARCHETYPE_CODE[spec.archetype]
    fast = int(spec.parameter_defaults.get("fast_period", 5))
    slow = int(spec.parameter_defaults.get("slow_period", 12))
    return f'''"""Generated by backtrader-agent from StrategySpec {spec.spec_hash}."""
import backtrader as bt


class GeneratedStrategy(bt.Strategy):
    params = (
        ("fast_period", {fast}),
        ("slow_period", {slow}),
    )

    def __init__(self):
{init_body}
        self._agent_buy_count = 0
        self._agent_sell_count = 0

    def next(self):
{next_body}

    def notify_order(self, order):
        if order.status == order.Completed:
            if order.isbuy():
                self._agent_buy_count += 1
            elif order.issell():
                self._agent_sell_count += 1
'''


def _pandas_custom_feed_source(dataset: Dict[str, Any]) -> str:
    classes = []
    branches = []
    for index, feed in enumerate(dataset.get("feeds", [])):
        if feed.get("format") != "pandas_custom_lines":
            continue
        canonical_columns = list(feed.get("canonical_columns", []))
        custom_lines = tuple(canonical_columns[7:])
        class_name = f"AgentPandasData{index}"
        parameters = tuple((line_name, line_name) for line_name in custom_lines)
        if custom_lines:
            classes.append(
                f"class {class_name}(bt.feeds.PandasData):\n"
                f"    lines = {custom_lines!r}\n"
                f"    params = {parameters!r}\n"
            )
        else:
            class_name = "bt.feeds.PandasData"
        branches.append(f'    if feed_name == {feed["name"]!r}:\n' f"        return {class_name}\n")
    body = "\n\n".join(classes)
    if body:
        body += "\n\n"
    return (
        body
        + "def _pandas_custom_feed_class(feed_name):\n"
        + "".join(branches)
        + '    raise RuntimeError("custom Pandas feed was not rendered for this dataset")\n'
    )


def _runner_source(spec: StrategySpec, dataset: Dict[str, Any]) -> str:
    custom_feed_source = _pandas_custom_feed_source(dataset)
    return f'''"""Controlled child-process entrypoint generated by backtrader-agent."""
import json
import math
import os

import backtrader as bt
import pandas as pd
from backtrader import TimeFrame

from strategy_{spec.module_slug} import GeneratedStrategy


TIMEFRAMES = {{
    "Ticks": TimeFrame.Ticks,
    "MicroSeconds": TimeFrame.MicroSeconds,
    "Seconds": TimeFrame.Seconds,
    "Minutes": TimeFrame.Minutes,
    "Days": TimeFrame.Days,
    "Weeks": TimeFrame.Weeks,
    "Months": TimeFrame.Months,
    "Years": TimeFrame.Years,
}}


class CanonicalBacktraderCSVData(bt.feeds.BacktraderCSVData):
    """Load canonical CAS rows through Backtrader's fixed CSV parser."""

    def _loadline(self, tokens):
        native = list(tokens[:7])
        native[0] = native[0][:10]
        return super()._loadline(native)


class CanonicalYahooCSVData(bt.feeds.YahooFinanceCSVData):
    """Adapt canonical CAS rows to the offline Yahoo parser contract."""

    def _loadline(self, tokens):
        native = [
            tokens[0][:10],
            tokens[1],
            tokens[2],
            tokens[3],
            tokens[4],
            tokens[4],
            tokens[5],
        ]
        return super()._loadline(native)


class CanonicalMT5CSVData(bt.feeds.GenericCSVData):
    """Controlled MT5 materialization adapter; input is already canonical CAS."""


{custom_feed_source}


def _csv_feed(descriptor):
    common = {{
        "dataname": descriptor["path"],
        "headers": True,
        "timeframe": TIMEFRAMES[descriptor["timeframe"]],
        "compression": descriptor["compression"],
    }}
    adapter = descriptor["adapter"]
    if adapter == "generic_csv":
        return bt.feeds.GenericCSVData(
            dtformat="%Y-%m-%dT%H:%M:%SZ",
            datetime=0,
            open=1,
            high=2,
            low=3,
            close=4,
            volume=5,
            openinterest=6,
            **common,
        )
    if adapter == "backtrader_csv":
        return CanonicalBacktraderCSVData(**common)
    if adapter == "yahoo_csv":
        return CanonicalYahooCSVData(
            reverse=False,
            adjclose=False,
            adjvolume=False,
            round=False,
            **common,
        )
    if adapter == "mt5_csv":
        return CanonicalMT5CSVData(
            dtformat="%Y-%m-%dT%H:%M:%SZ",
            datetime=0,
            open=1,
            high=2,
            low=3,
            close=4,
            volume=5,
            openinterest=6,
            **common,
        )
    raise RuntimeError("CSV dataset adapter is not product-allowlisted")


def _pandas_feed(descriptor):
    frame = pd.read_csv(
        descriptor["path"],
        parse_dates=["datetime"],
    )
    feed_class = (
        _pandas_custom_feed_class(descriptor["name"])
        if descriptor["adapter"] == "pandas_custom_lines"
        else bt.feeds.PandasData
    )
    parameters = {{
        "dataname": frame,
        "datetime": "datetime",
        "open": "open",
        "high": "high",
        "low": "low",
        "close": "close",
        "volume": "volume",
        "openinterest": "openinterest",
        "timeframe": TIMEFRAMES[descriptor["timeframe"]],
        "compression": descriptor["compression"],
    }}
    return feed_class(**parameters)


def _load_feed(descriptor):
    adapter = descriptor["adapter"]
    if adapter in {{
        "generic_csv",
        "backtrader_csv",
        "yahoo_csv",
        "mt5_csv",
    }}:
        return _csv_feed(descriptor)
    if adapter in {{"pandas", "pandas_custom_lines"}}:
        return _pandas_feed(descriptor)
    raise RuntimeError("dataset adapter is not product-allowlisted")


def _nested(value, *parts, default=None):
    current = value
    for part in parts:
        if not isinstance(current, dict) or part not in current:
            return default
        current = current[part]
    return current


def _execute():
    descriptors = json.loads(os.environ["BACKTRADER_AGENT_DATASETS_JSON"])
    mode = os.environ.get("BACKTRADER_AGENT_MODE", "runonce")
    cerebro = bt.Cerebro(stdstats=False)
    for descriptor in descriptors:
        feed = _load_feed(descriptor)
        transform = descriptor.get("transform")
        if transform is None:
            cerebro.adddata(feed, name=descriptor["name"])
        else:
            parameters = transform["parameters"]
            if transform["profile_id"] == "resample":
                cerebro.resampledata(
                    feed,
                    name=descriptor["name"],
                    timeframe=TIMEFRAMES[parameters["timeframe"]],
                    compression=parameters["compression"],
                )
            elif transform["profile_id"] == "replay":
                cerebro.replaydata(
                    feed,
                    name=descriptor["name"],
                    timeframe=TIMEFRAMES[parameters["timeframe"]],
                    compression=parameters["compression"],
                )
            else:
                raise RuntimeError("dataset transform is not product-allowlisted")
    start_cash = {float(spec.value.get("cash", 100000.0))!r}
    cerebro.broker.setcash(start_cash)
    cerebro.broker.setcommission(commission={float(spec.value.get("commission", 0.0))!r})
    cerebro.addstrategy(GeneratedStrategy)
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name="trades")
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name="drawdown")
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name="sharpe")
    cerebro.addanalyzer(bt.analyzers.Returns, _name="returns")
    strategies = cerebro.run(runonce=(mode == "runonce"))
    strategy = strategies[0]
    trade = strategy.analyzers.trades.get_analysis()
    drawdown = strategy.analyzers.drawdown.get_analysis()
    sharpe = strategy.analyzers.sharpe.get_analysis()
    returns = strategy.analyzers.returns.get_analysis()
    final_value = float(cerebro.broker.getvalue())
    trade_count = int(_nested(trade, "total", "closed", default=0) or 0)
    won = int(_nested(trade, "won", "total", default=0) or 0)
    lost = int(_nested(trade, "lost", "total", default=0) or 0)
    metrics = {{
        "bar_num": int(len(strategy)),
        "buy_count": int(strategy._agent_buy_count),
        "sell_count": int(strategy._agent_sell_count),
        "win_count": won,
        "loss_count": lost,
        "trade_num": trade_count,
        "final_value": final_value,
        "sharpe_ratio": sharpe.get("sharperatio") if isinstance(sharpe, dict) else None,
        "annual_return": float(returns.get("rnorm", 0.0) or 0.0),
        "max_drawdown": float(_nested(drawdown, "max", "drawdown", default=0.0) or 0.0),
        "return_rate": ((final_value / start_cash - 1.0) * 100.0) if start_cash else 0.0,
    }}
    for value in metrics.values():
        if isinstance(value, float) and not math.isfinite(value):
            raise RuntimeError("non-finite metric")
    return metrics


if __name__ == "__main__":
    print("BACKTRADER_AGENT_RESULT=" + json.dumps({{"metrics": _execute()}}, sort_keys=True))
'''


def _single_test_source(spec: StrategySpec, dataset: Dict[str, Any]) -> str:
    strategy = _strategy_source(spec)
    runner = _runner_source(spec, dataset).replace(
        f"from strategy_{spec.module_slug} import GeneratedStrategy\n\n", ""
    )
    runner = runner.replace('if __name__ == "__main__":\n', "def test_generated_strategy():\n")
    runner = runner.replace(
        '    print("BACKTRADER_AGENT_RESULT=" + json.dumps({"metrics": _execute()}, sort_keys=True))',
        "    metrics = _execute()\n"
        '    assert metrics["final_value"] is not None\n'
        '    print("BACKTRADER_AGENT_RESULT=" + json.dumps({"metrics": metrics}, sort_keys=True))',
    )
    return strategy + "\n\n" + runner


def _config_source(spec: StrategySpec, dataset: Dict[str, Any]) -> str:
    return f"""schema_version: generated-config-v1
strategy:
  name: {spec.value['name']}
  slug: {spec.slug}
  archetype: {spec.archetype}
dataset_id: {dataset['dataset_id']}
dataset_manifest_hash: {dataset['manifest_hash']}
cash: {float(spec.value.get('cash', 100000.0))}
commission: {float(spec.value.get('commission', 0.0))}
execution_modes:
  - runonce
  - runnext
"""


class ArtifactRenderer:
    def __init__(self, state_root: Path) -> None:
        self.state_root = Path(state_root)

    def render(
        self, session_id: str, spec: StrategySpec, dataset: Dict[str, Any]
    ) -> Dict[str, Any]:
        if not SESSION_RE.fullmatch(session_id):
            raise AgentError("BTAG-SESSION-ID", "session ID is malformed")
        if dataset.get("dataset_id") != spec.value["dataset_id"]:
            raise AgentError("BTAG-RENDER-DATASET", "StrategySpec dataset ID does not match")
        revision = hash_object(
            {
                "spec_hash": spec.spec_hash,
                "dataset_hash": dataset.get("manifest_hash"),
                "renderer": "scaffold-v1",
            }
        )[:20]
        draft_root = self.state_root / "sessions" / session_id / "drafts" / revision
        if spec.profile == "python_bundle":
            file_contents = {
                "config.yaml": _config_source(spec, dataset).encode("utf-8"),
                f"strategy_{spec.module_slug}.py": _strategy_source(spec).encode("utf-8"),
                "run.py": _runner_source(spec, dataset).encode("utf-8"),
            }
            roles = {
                "config.yaml": "config",
                f"strategy_{spec.module_slug}.py": "strategy",
                "run.py": "runner",
            }
            entrypoint = "run.py"
        else:
            name = f"test_{spec.slug}.py"
            file_contents = {name: _single_test_source(spec, dataset).encode("utf-8")}
            roles = {name: "strategy"}
            entrypoint = name
        draft_root.mkdir(parents=True, exist_ok=True)
        files: List[Dict[str, Any]] = []
        for relative_path, content in sorted(file_contents.items()):
            destination = draft_root / relative_path
            if destination.exists() and destination.read_bytes() != content:
                raise AgentError("BTAG-DRAFT-CONFLICT", "draft revision has conflicting bytes")
            if not destination.exists():
                atomic_write_bytes(destination, content, create_only=True)
            files.append(
                {
                    "path": relative_path,
                    "role": roles[relative_path],
                    "sha256": sha256_bytes(content),
                    "bytes": len(content),
                }
            )
        portable = {
            "schema_version": "artifact-manifest-v1",
            "artifact_id": f"artifact-{revision}",
            "slug": spec.slug,
            "spec_hash": spec.spec_hash,
            "dataset_id": dataset["dataset_id"],
            "output_profile": spec.profile,
            "files": files,
            "extensions": {
                "backtrader_agent": {
                    "generated_by": "backtrader-agent",
                    "renderer_version": "scaffold-v1",
                    "session_id": session_id,
                    "archetype": spec.archetype,
                    "dataset_manifest_hash": dataset["manifest_hash"],
                    "entrypoint": entrypoint,
                }
            },
        }
        portable["artifact_hash"] = hash_object(portable)
        manifest_path = draft_root / "artifact-manifest.json"
        if manifest_path.exists():
            existing = manifest_path.read_bytes()
            expected = canonical_json_bytes(portable) + b"\n"
            if existing != expected:
                raise AgentError("BTAG-DRAFT-MANIFEST", "draft manifest conflicts")
        else:
            atomic_write_json(manifest_path, portable, create_only=True)
        state_root = self.state_root.resolve()
        resolved_draft = draft_root.resolve(strict=True)
        try:
            draft_relative = resolved_draft.relative_to(state_root).as_posix()
        except ValueError as exc:
            raise AgentError(
                "BTAG-DRAFT-PATH", "private draft must remain inside state root"
            ) from exc
        record_payload: Dict[str, Any] = {
            "schema_version": "artifact-provenance-v1",
            "generated_by": "backtrader-agent",
            "renderer_version": "scaffold-v1",
            "session_id": session_id,
            "artifact_hash": portable["artifact_hash"],
            "spec_hash": spec.spec_hash,
            "dataset_id": dataset["dataset_id"],
            "dataset_manifest_hash": dataset["manifest_hash"],
            "draft_relative_path": draft_relative,
            "manifest_sha256": sha256_bytes(manifest_path.read_bytes()),
        }
        record_payload["record_hash"] = hash_object(record_payload)
        record = {
            **record_payload,
            "signature": TokenAuthority(self.state_root).sign_product_record(record_payload),
        }
        record_path = (
            self.state_root
            / "sessions"
            / session_id
            / "artifacts"
            / f"{portable['artifact_hash']}.json"
        )
        if record_path.exists():
            if read_json(record_path) != record:
                raise AgentError(
                    "BTAG-PROVENANCE-CONFLICT",
                    "artifact provenance record conflicts with the rendered bytes",
                )
        else:
            atomic_write_json(record_path, record, create_only=True)
        return {
            **portable,
            "_draft_path": str(draft_root),
            "_artifact_record_hash": record_payload["record_hash"],
        }
